### ISSUE TITLE
Zadig needed to install drivers on Win10

### ISSUE THREAD

**Issue by fnafnio** [probe-rs/hs-probe-firmware#25]
I'm on Windows 10 build 19042.1165

After connecting the HS-Probe, Zadig was needed to install drivers for the CMSIS-DAP interfaces. Zadig showed `NONE` as the currently installed driver.
After installing WinUSB drivers, I was able to update the firmware to latest master with dfu-util and connect to a target for flashing/debugging etc.

The USB-VCOM doesn't show up in the COM-Port list, the device manager lists the device status as

```
This device cannot start. (Code 10)

A device which does not exist was specified.
```

I will try on other devices as well. Let me know if I can gather more information somehow

**Comment by mattico** [comment]
I had it show up as multiple interfaces with the same/similar names
![image](https://user-images.githubusercontent.com/853158/132538648-5c2cbd5e-464e-4425-b602-eac1680bbd53.png)

- "Interface 2" had the driver "usbser (v10.0.19041.906)"
- "Interface 0" had the driver "HidUsb (v10.0.19041.868)"
- The rest had no driver, so I installed the WinUSB driver with Zadig.

The CMSIS-DAP interface works now, but the serial port does not. I'll try updating the firmware with DFU.

**Comment by mattico** [comment]
The probe shows up in dfu-util as `Found Runtime: [1209:4853] ver=0010, devnum=17, cfg=1, intf=4, path="1-1.1", alt=0, name="UNKNOWN", serial="0d001c001650563641333620"` but I can't do anything with the probe.

```
$ dfu-util -n 13 -U fw.bin
dfu-util 0.10

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2020 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

ID 1209:4853
Run-time device DFU version 0100
Claiming USB DFU Runtime Interface...
Determining device status: state = appIDLE, status = 0
Device really in Runtime Mode, send DFU detach request...
error detaching
Device will detach and reattach...
Lost device after RESET?
```

Then it doesn't show up in dfu-util until I unplug it.

**Comment by mattico** [comment]
The same probe does flash fine with dfu-util under linux.
