### ISSUE TITLE
Probe cannot connect to the ATSAME51N target

### ISSUE THREAD

**Issue by vccggorski** [probe-rs/hs-probe-firmware#29]
Issue: HS-probe cannot connect to the ATSAME51N target (other targets not checked) since commit https://github.com/probe-rs/hs-probe-firmware/commit/352679b till newest master. 

## How to reproduce:
`$ openocd -d -f 'interface/cmsis-dap.cfg' -c 'transport select swd' -f 'target/atsame5x.cfg'`

should result in

```
Info : Using CMSIS-DAPv2 interface with VID:PID=0x1209:0x4853, serial=330048000851363131383236
Info : CMSIS-DAP: SWD  supported
Info : CMSIS-DAP: JTAG supported
Info : CMSIS-DAP: SWO-UART supported
Info : CMSIS-DAP: SWO streaming trace supported
Info : CMSIS-DAP: FW Version = 49c1faa
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 0 TDI = 0 TDO = 1 nTRST = 1 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Error: Error connecting DP: cannot read IDR
```

It might be able to connect to target accidently in case it is being hot-plugged. After target reset the error should get reproduced just fine.

relevant debug log for OpenOCD
```
Debug: 96 62 transport.c:230 handle_transport_init(): handle_transport_init
Debug: 97 62 command.c:166 script_debug(): command - dap init
Debug: 98 62 arm_dap.c:107 dap_init_all(): Initializing all DAPs ...
Debug: 99 64 cmsis_dap.c:1113 cmsis_dap_swd_switch_seq(): JTAG-to-SWD
Debug: 100 70 cmsis_dap.c:880 cmsis_dap_swd_read_process(): CMSIS-DAP Protocol Error @ 1 (wrong parity)
Debug: 101 73 cmsis_dap.c:1113 cmsis_dap_swd_switch_seq(): JTAG-to-SWD
Debug: 102 79 cmsis_dap.c:880 cmsis_dap_swd_read_process(): CMSIS-DAP Protocol Error @ 1 (wrong parity)
Debug: 103 82 cmsis_dap.c:1113 cmsis_dap_swd_switch_seq(): JTAG-to-SWD
Debug: 104 88 cmsis_dap.c:880 cmsis_dap_swd_read_process(): CMSIS-DAP Protocol Error @ 1 (wrong parity)
...repeats until time out...
```

I think that OpenOCD fails on an errornous response from HS-Probe during `DAP_Transfer` command which is a result of an invalid debugging session state that was not properly initialized in `DAP_SWJ_Sequence` command which returned false positive to OpenOCD earlier on.

## Hot patch for master

Upon closer inspection, I managed to get it working back again by restoring old SWD code path from https://github.com/probe-rs/hs-probe-firmware/commit/253c8fe (commit earlier).

```diff
diff --git a/firmware/src/dap.rs b/firmware/src/dap.rs
index d74c4c7..ecc9ddd 100644
--- a/firmware/src/dap.rs
+++ b/firmware/src/dap.rs
@@ -550,9 +550,7 @@ impl<'a> DAP<'a> {
 
         match self.mode {
             Some(DAPMode::SWD) => {
-                self.pins.jtag_mode();
-                self.jtag.tms_sequence(seq, nbits);
-                self.pins.swd_mode();
+                self.swd.tx_sequence(seq);
             }
             Some(DAPMode::JTAG) => {
                 self.jtag.tms_sequence(seq, nbits);
diff --git a/firmware/src/swd.rs b/firmware/src/swd.rs
index c10b22e..eaae354 100644
--- a/firmware/src/swd.rs
+++ b/firmware/src/swd.rs
@@ -106,6 +106,14 @@ impl<'a> SWD<'a> {
         self.wait_retries = wait_retries;
     }
 
+    pub fn tx_sequence(&self, sequence: &[u8]) {
+        self.pins.swd_tx();
+        for byte in sequence {
+            self.spi.tx8(*byte);
+        }
+        self.spi.wait_busy();
+    }
+
     pub fn idle_low(&self) {
         self.spi.tx4(0x0);
     }
```

I didn't have an opportunity to compare the SWD traffic done through SPI (old code in `Swd::tx_sequence`) and raw bitbanging (new code in `Jtag::tms_sequence`) but there might be some timing issues that (maybe) atsame51n's DSU/ADI is just too sensitive to process?

Thanks in advance for taking time and looking into this :)

**Comment by adamgreig** [comment]
This turned out to be caused by a custom hardware implementation of hs-probe which omitted the JTAG SPI2 CLK pin which should be wired together with the SPI1 CLK pin. At the time, the firmware did not use the JTAG CLK so the issue wasn't noticed, but after 352679b, the firmware uses JTAG mode to transition to SWD mode (since it's faster as it can use the SPI peripheral instead of bitbanging), which caused this apparent bug as no clock signal was driven during the transition sequence. [Chat logs about it here](https://matrix.to/#/!vhKMWjizPZBgKeknOo:matrix.org/$5AwRwmM1uqe47gFEaDtFmzMX2wFo21VepZtEkAZFauc?via=matrix.org).

So in the end, it's a hardware issue outside of probe-rs, and at least a simple workaround is possible.
